CREATE TABLE IF NOT EXISTS models (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    FIO VARCHAR(50) NOT NULL,
    gender VARCHAR(13) NOT NULL,
    number_phone VARCHAR(13) NOT NULL,
    height INT NOT NULL,
    weight INT NOT NULL
);
CREATE TABLE IF NOT EXISTS countries (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    shortname VARCHAR(3) NOT NULL,
    name VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS customer_organizations (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL,
    country_id INTEGER REFERENCES countries(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    contact_details VARCHAR(30) NOT NULL,
    inn INT NOT NULL,
    confirmed BOOLEAN DEFAULT false
);
CREATE TABLE IF NOT EXISTS events (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL,
    country_id INTEGER REFERENCES countries(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  	customer_organization_id INTEGER REFERENCES customer_organizations(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    date  DATE NOT NULL, 
);
CREATE TABLE IF NOT EXISTS contracts(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    event_id INTEGER REFERENCES events(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    model_id INTEGER REFERENCES models(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    payment DECIMAL(15,2)
);
CREATE TABLE IF NOT EXISTS administrators(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    FIO VARCHAR(50) NOT NULL,
    number_phone VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS roles(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL,
    permission VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS users(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    login VARCHAR(20) NOT NULL,
    password VARCHAR(30) NOT NULL,
    customer_organization_id INTEGER REFERENCES customer_organizations(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    administrator_id INTEGER REFERENCES administrators(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE ON UPDATE NO ACTION
);